#!/bin/bash

#newrm-A replacement for the existing rm command
# This script procides a rudimentary unremove capability by creating
# and utilizing a new directorywithin the user's home directorywithin
# It can handle directories of content as well as individual files.
# If the user specifies the -f flag, giles are removed and NOT archived

archivedir="$HOME/.deleted-files"
realrm="$(which rm)"
copy="$(which cp) -R"
if [ $# -eq 0 ] ; then
    exec $realrm
fi

#Parse all options looking for '-f'

flags=""

while getopts "dfiPRrvW" opt 
do 
    case $opt in 
        f ) exec $realrm "$@"   ;; 
        * ) flags="$flags -$opt"  ;;
    esac
done
shift $(( $OPTIND -1 ))

#BEGIN MAIN script

if [ ! -d $archivedir ] ; then
    if [ ! -w $HOME ] ; then
        echo "$0 failed: can't create $archivedir in $HOME" >&2
        exit 1
    fi 
    mkdir $archivedir
    chmod 700 $archivedir
fi 

for arg
do
    newname="$archivedir/$(date "+%S.%M.%H.%d.%m").$basename "$arg")"
    if [ -f "$arg" -o -d "$arg" ] ; then
        $copy "$arg" "$newname"
    fi 
done 

exec $realrm $flags "$@" 