#!/bin/bash

#hilow--A simple number guessing game

biggest=100         #Maximum number possible
guess=0             #Guessed by player
guesses=0           #Number of guess made
$(( $RANDOM % $biggest + 1 )) #Random number, between 1 and $biggest
echo "Guess a number between 1 and $biggest

while [ "$guess" -ne $number ] ; do
    /bin/echo -n "Guess? ; read answer
    if [ "$guess" -lt  number ] ; then
        echo "...bigger!"
    elif [ "$guess" -gt $number ] ; then
        echo "...smaller!"
    fi
    guess=$(($guesses  + 1 ))
done

echo "Right!! Guessed #number in $guesses guesses."

exit 0
